import Head from 'next/head';
import { generateUrl } from 'utils';
import { styled } from '@mui/material';

const HOME = styled("div")(() => ({
  padding: "0 2rem",
  height: "100vh"
}))

const Home = () => {
  return (
    <HOME>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={generateUrl("favicon.ico")} />
      </Head>
      {/* <main className={styles.main}>
      </main> */}
    </HOME>
  )
}

export default Home;
