import Head from 'next/head'
import type { NextPage } from 'next'
import ThemeSwitcher from '../components/ThemeSwitcher'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeSwitcher />
      <main className={styles.main}>
      </main>
    </div>
  )
}

export default Home
