import Head from 'next/head';
import { generateUrl } from 'utils';
import { styled } from '@mui/material';

const HOME = styled("div")(() => ({
  padding: "0 2rem",
  // height: "100vh",
  '& main': {
    minHeight: "100vh",
    padding: "4rem 0",
    flex: 1,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    '& .title': {
      margin: 0,
      lineHeight: 1.15,
      fontSize: "4rem",
      textAlign: "center",
      "& a": {
        color: "#0070f3",
        textDecoration: "none",
        '&:hover, &:focus, &:active': {
          textDecoration: "underline",
        },
      }
    },
    '& .description': {
      textAlign: "center",
      '& .code': {
        background: "#fafafa",
        borderRadius: 5,
        padding: "0.75rem",
        fontSize: "1.1rem",
        fontFamily: "Menlo, Monaco, Lucida Console, Liberation Mono, DejaVu Sans Mono, Bitstream Vera Sans Mono, Courier New, monospace",
      }
    },
    '& .grid': {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      flexWrap: "wrap",
      maxWidth: 800,
      '& .card': {
        margin: "1rem",
        padding: "1.5rem",
        textAlign: "left",
        color: "inherit",
        textDecoration: "none",
        border: "1px solid #eaeaea",
        borderRadius: 10,
        transition: "color 0.15s ease, border-color 0.15s ease",
        maxWidth: 300,
        '&:hover, &:focus, &:active': {
          color: "#0070f3",
          borderColor: "#0070f3",
        },
        '& h2': {
          margin: "0 0 1rem 0",
          fontSize: "1.5rem",
        },
        '& p': {
          margin: 0,
          fontSize: "1.25rem",
          lineHeight: 1.5,
        }
      }
    }
  }
}))

const Home = () => {
  return (
    <HOME>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={generateUrl("favicon.ico")} />
      </Head>
      <main className={"main"}>
        <h1 className={"title"}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={"description"}>
          Get started by editing{' '}
          <code className={"code"}>pages/index.tsx</code>
        </p>

        <div className={"grid"}>
          <a href="https://nextjs.org/docs" className={"card"}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={"card"}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={"card"}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={"card"}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>
    </HOME>
  )
}

export default Home;
